# Generated by Django 3.1 on 2023-12-15 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
    ]
